version: "3"

services:
  db:
    image: mariadb:10.3.12
    restart: unless-stopped
    environment:
      MYSQL_USER: tgabot
      MYSQL_PASSWORD: tgabot
      MYSQL_DATABASE: tgabot
      MYSQL_ROOT_PASSWORD: tgabot
    volumes:
      - 'db-data:/var/lib/mysql'
      - './conf/mysql:/etc/mysql/conf.d'
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - './config:/tgabot/config'
    depends_on:
      - db
volumes:
  db-data:
    driver: 'local'